### ISSUE TITLE
数组越界问题

### ISSUE THREAD

**Issue by changxiaoyao227** [lianli-o/diy_compiler#1]
报错在Class Production 显示segement fault  好像是vector数组越界

**Comment by ruikangliu** [comment]
代码有做什么改动吗？还是改了源程序之后就运行报错呢？可否发一下改动的地方或者报错的源程序？

**Comment by ruikangliu** [comment]
这个问题可能是因为 main.cpp 里的 path_prefix 没有加上最后的 /，例如路径应写为 "E:/Workspace/" 而不是 "E:/Workspace"
