### ISSUE TITLE
运行报错 

### ISSUE THREAD

**Issue by lmfs-bear** [lianli-o/diy_compiler#2]
https://user-images.githubusercontent.com/77051768/166646151-0a4f45a7-5d4f-4cc7-872a-b2f2eded55c6.png

**Comment by lmfs-bear** [comment]
用原始的grammer.txt会报如下错误
![image](https://user-images.githubusercontent.com/77051768/166646151-0a4f45a7-5d4f-4cc7-872a-b2f2eded55c6.png)

**Comment by ruikangliu** [comment]
这个是正常的，因为 if-then-if-then-else 语句本身就具有二义性，程序里会在语义分析阶段自动解决这个问题的
